Moved resolvers from entrypoint to start script

diff --git a/usr/bin/start b/usr/bin/start
--- a/usr/bin/start
+++ b/usr/bin/start
@@ -1,6 +1,13 @@
 #!/bin/bash
 set -e
 
+# Compute the DNS resolvers for use in the templates - if the IP contains ":", it's IPv6 and must be enclosed in []
+export RESOLVERS=$(awk '$1 == "nameserver" {print ($2 ~ ":")? "["$2"]": $2}' ORS=' ' /etc/resolv.conf | sed 's/ *$//g')
+if [ "x$RESOLVERS" = "x" ]; then
+    echo "Warning: unable to determine DNS resolvers for nginx" >&2
+    unset RESOLVERS
+fi
+
 rm -f Procfile
 # Allow docker-gen to be disabled
 if [[ ${DISABLE_DOCKER_GEN} != "true"  ]]; then
